version: '3.8'

services:
  shuffle:
    container_name: shuffle
    hostname: shuffle
    build:
      context: ./service-shuffle
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    environment:
      SERVER_PORT: 8080
      SHUFFLE_LOG_URL: http://log:8080/api/v1/logs
    networks:
      - demo-network
  log:
    container_name: log
    hostname: log
    build:
      context: ./service-log
      dockerfile: Dockerfile
    ports:
      - 8086:8080
    environment:
      SERVER_PORT: 8080
    networks:
      - demo-network

networks:
  demo-network:
